ios-workflow:
  name: iOS Workflow
  instance_type: mac_mini_m1
  environment:
    xcode: 15.0 # <-- Set Xcode version to 15 or newer
    groups:
      - ios_credentials
    vars:
      BUNDLE_ID: "io.codemagic.ftlflutter"
      TEST_BUNDLE_ID: "io.codemagic.ftlflutter.uitests.xctrunner"
  scripts:
    - name: Keychain setup
      script: |
        keychain initialize
        app-store-connect fetch-signing-files ${BUNDLE_ID} --create
        app-store-connect fetch-signing-files ${TEST_BUNDLE_ID} --create
        keychain add-certificates
        xcode-project use-profiles --code-signing-setup-verbose-logging

    - name: Build app for testing
      script: |
        set -ex
        flutter build ios --release
        cd ios
        xcodebuild \
          -workspace Runner.xcworkspace \
          -scheme Runner \
          -config Flutter/Release.xcconfig \
          -derivedDataPath "../build/ios_integ" \
          -sdk iphoneos \
          build-for-testing

    - name: Package tests bundle
      script: |
        set -ex
        cd ./build/ios_integ/Build/Products
        zip -r "ios_tests.zip" *-iphoneos *.xctestrun

    - name: Run tests in Firebase Test Lab
      script: |
        gcloud firebase test ios run --test "build/ios_integ/Build/Products/ios_tests.zip"

  artifacts:
    - "**/ios_tests.zip"
